M48
; DRILL file {KiCad 6.0.6} date Mon 25 Jul 2022 01:00:01 PM UTC
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-25T13:00:01+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.4724Y-3.2677
X5.4724Y-4.1339
X6.3386Y-3.2677
X6.3386Y-4.1339
T0
M30
